# Quantitative Value Strategy

"Value investing" means investing in the stoks that are cheapest relative to common measures of business value (like earnings or assets).

For this project, we're going to build an investing strategy that selects the 50 stocks with the best value metrics. From there, we will calculate recommended trades for an equal-weight portifolio of these 50 stocks.

# Library imports

In [3]:
from scipy.stats import percentileofscore as score
from scipy import stats
import pandas as pd
import numpy as np 
import xlsxwriter 
import requests
import math

# Importing Our List of Stocks and getting API Token

In [4]:
stocks = pd.read_csv('sp_500_stocks.csv')
IEX_CLOUD_API_TOKEN = 'Tpk_059b97af715d417d9f49f50b51b1c448'
symbol = 'AAPL'
api_url = f'https://sandbox.iexapis.com/stable/stock/{symbol}/stats/?token={IEX_CLOUD_API_TOKEN}'
data = requests.get(api_url).json()

data

{'companyName': 'Apple Inc',
 'marketcap': 2179710091582,
 'week52high': 186.93,
 'week52low': 132.55,
 'week52highSplitAdjustOnly': 190.03,
 'week52lowSplitAdjustOnly': 133.12,
 'week52change': 8.81991082668745e-05,
 'sharesOutstanding': 16214389069,
 'float': 0,
 'avg10Volume': 112989985,
 'avg30Volume': 92786900,
 'day200MovingAvg': 167.74,
 'day50MovingAvg': 150.56,
 'employees': 148219,
 'ttmEPS': 6.26,
 'ttmDividendRate': 0.8934875364769191,
 'dividendYield': 0.007068606066796291,
 'nextDividendDate': '',
 'exDividendDate': '2022-04-26',
 'nextEarningsDate': '2022-07-19',
 'peRatio': 21.66131715544546,
 'beta': 1.2955158694460418,
 'maxChangePercent': 50.48162656352401,
 'year5ChangePercent': 2.896969729956641,
 'year2ChangePercent': 0.5247876954570004,
 'year1ChangePercent': 0.014789143385774263,
 'ytdChangePercent': -0.2597888830234596,
 'month6ChangePercent': -0.2300527650808095,
 'month3ChangePercent': -0.2049464125669978,
 'month1ChangePercent': -0.0442465374668452,
 'day30ChangePercent': -0.04437188516544067,
 'day5ChangePercent': -0.002529233028227558}

# Executing a batch API Call & Building our Dataframe

In [5]:
#1.Split the list of tickers in sublists.

#2. Using chuncks function
#2.1. Source: https://stackoverflow.com/questions/312443/how-do-you-split-a-list-into-evenly-sized-chunks

#3. See batch requests in IEX API documentation

def chunks(lst,n):
    """Yield successive n-sized chunks from lst."""
    for i in range(0, len(lst), n):
        yield lst[i : i + n]

In [6]:
symbol_groups = list(chunks(stocks['Ticker'],100))
symbol_strings = []
for i in range(0, len(symbol_groups)):
    
    symbol_strings.append(','.join(symbol_groups[i]))
    #print (symbol_strings[i])
    
my_columns = ['Ticker','Company Name', 'Price', 'Price-to-Earnings Ratio', 'Number of Shares to Buy']

In [7]:
final_dataframe = pd.DataFrame(columns = my_columns)

for symbol_string in symbol_strings[:1]:
    batch_api_call_url = f'https://sandbox.iexapis.com/stable/stock/market/batch?symbols={symbol_string} &types=price,stats&token={IEX_CLOUD_API_TOKEN}'
    data = requests.get(batch_api_call_url).json()

    for symbol in symbol_string.split(','):
    
        final_dataframe= final_dataframe.append(
        pd.Series(
        [
            symbol,
            data[symbol]['stats']['companyName'],
            data[symbol]['price'],
            data[symbol]['stats']['peRatio'],
            'N/A'
        ],
        index = my_columns),
        ignore_index = True)
        
final_dataframe.head(50)

,Ticker,Company Name,Price,Price-to-Earnings Ratio,Number of Shares to Buy
0,AAP,Advance Auto Parts Inc,176.080,18.097125,N/A
1,AAPL,Apple Inc,142.030,21.660434,N/A
2,ABBV,Abbvie Inc,150.370,20.648383,N/A
3,ABC,Amerisource Bergen Corp.,146.210,17.844214,N/A
4,ABMD,Abiomed Inc.,238.250,77.915621,N/A
5,ABT,Abbott Laboratories,104.490,23.445273,N/A
6,ACN,Accenture plc,285.900,28.843976,N/A
7,ADBE,Adobe Inc,375.250,36.428972,N/A
8,ADI,Analog Devices Inc.,151.800,46.252414,N/A
9,ADM,Archer Daniels Midland Co.,82.900,14.575706,N/A
10,ADP,Automatic Data Processing Inc.,212.590,30.447007,N/A
11,ADSK,Autodesk Inc.,170.010,75.742269,N/A
12,AEE,Ameren Corp.,82.730,20.854371,N/A
13,AEP,American Electric Power Company Inc.,91.640,18.048717,N/A
14,AES,AES Corp.,20.580,-91.371167,N/A
15,AFL,Aflac Inc.,56.600,8.485949,N/A
16,AIG,American International Group Inc,52.520,4.222994,N/A
17,AIV,Apartment Investment & Management Co.,5.960,-50.203614,N/A
18,AIZ,Assurant Inc,172.490,6.912145,N/A
19,AJG,Arthur J. Gallagher & Co.,155.760,33.582875,N/A
20,AKAM,Akamai Technologies Inc,91.760,23.423210,N/A
21,ALB,Albemarle Corp.,226.470,92.273603,N/A
22,ALGN,"Align Technology, Inc.",231.830,27.370360,N/A
23,ALK,Alaska Air Group Inc.,40.590,11.327236,N/A
24,ALL,Allstate Corp (The),123.600,9.682095,N/A
25,ALLE,Allegion plc,97.310,18.684417,N/A
26,ALXN,Alexion Pharmaceuticals Inc.,190.900,0.000000,N/A
27,AMAT,Applied Materials Inc.,97.100,11.947162,N/A
28,AMCR,Amcor Plc,12.210,19.013931,N/A
29,AMD,Advanced Micro Devices Inc.,83.970,39.534534,N/A
30,AME,Ametek Inc,110.670,23.761659,N/A
31,AMGN,AMGEN Inc.,240.870,22.429924,N/A
32,AMP,Ameriprise Financial Inc,245.800,8.683891,N/A
33,AMT,American Tower Corp.,257.730,42.565791,N/A
34,AMZN,Amazon.com Inc.,110.050,51.763046,N/A
35,ANET,Arista Networks Inc,97.870,30.209596,N/A
36,ANSS,Ansys Inc.,243.070,45.216765,N/A
37,ANTM,Anthem Inc,480.650,17.649142,N/A
38,AON,Aon plc.,258.040,0.000000,N/A
39,AOS,A.O. Smith Corp.,53.350,17.285430,N/A
40,APA,APA Corporation,41.785,5.453791,N/A
41,APD,Air Products & Chemicals Inc.,242.750,23.952589,N/A
42,APH,Amphenol Corp.,64.190,23.234777,N/A
43,APTV,Aptiv PLC,91.460,74.140461,N/A
44,ARE,Alexandria Real Estate Equities Inc.,136.370,55.302827,N/A
45,ATO,Atmos Energy Corp.,106.230,20.039385,N/A
46,ATVI,Activision Blizzard Inc,77.940,24.169517,N/A
47,AVB,Avalonbay Communities Inc.,196.100,24.017482,N/A
48,AVGO,Broadcom Inc,527.000,23.357836,N/A
49,AVY,Avery Dennison Corp.,157.170,18.117876,N/A

# Removing Glamour Stocks

The opposite of a "value stock" is a "glamour stock". 
Since the goal of this strategy is to identify the 50 best value stocks from our universe, our 
next step is ro remove glamour stocks from the DataFrame. 

We'll sort the DataFrame by the stocks' price-to-earnings ratio, and drop all stocks outside the
top 50.

In [8]:
final_dataframe.sort_values('Price-to-Earnings Ratio', ascending = True, inplace = True)
final_dataframe = final_dataframe[final_dataframe['Price-to-Earnings Ratio'] > 0]

#Returning the top 10
final_dataframe = final_dataframe[:10]
final_dataframe.reset_index(inplace=True)
final_dataframe.drop('index', axis = 1, inplace = True)

final_dataframe

,Ticker,Company Name,Price,Price-to-Earnings Ratio,Number of Shares to Buy
0,AIG,American International Group Inc,52.520,4.222994,N/A
1,C,Citigroup Inc,48.220,5.400710,N/A
2,APA,APA Corporation,41.785,5.453791,N/A
3,BEN,"Franklin Resources, Inc.",25.260,6.445564,N/A
4,CE,Celanese Corp,129.900,6.648120,N/A
5,AIZ,Assurant Inc,172.490,6.912145,N/A
6,BBY,Best Buy Co. Inc.,72.390,7.340841,N/A
7,AFL,Aflac Inc.,56.600,8.485949,N/A
8,AMP,Ameriprise Financial Inc,245.800,8.683891,N/A
9,BAC,Bank Of America Corp.,32.940,8.906512,N/A

# Calculating the number os shares to buy

In [9]:
portifolio_input = 100000
position_size = float(portifolio_input)/len(final_dataframe.index)

for row in final_dataframe.index:
    final_dataframe.loc[row, 'Number of Shares to Buy'] = math.floor(position_size/final_dataframe.loc[row, 'Price'])

final_dataframe

,Ticker,Company Name,Price,Price-to-Earnings Ratio,Number of Shares to Buy
0,AIG,American International Group Inc,52.520,4.222994,190
1,C,Citigroup Inc,48.220,5.400710,207
2,APA,APA Corporation,41.785,5.453791,239
3,BEN,"Franklin Resources, Inc.",25.260,6.445564,395
4,CE,Celanese Corp,129.900,6.648120,76
5,AIZ,Assurant Inc,172.490,6.912145,57
6,BBY,Best Buy Co. Inc.,72.390,7.340841,138
7,AFL,Aflac Inc.,56.600,8.485949,176
8,AMP,Ameriprise Financial Inc,245.800,8.683891,40
9,BAC,Bank Of America Corp.,32.940,8.906512,303

# Build a Better (and More Realistic) Value Strategy

Every valuation metric has certain flaws.

For example, the price-to-earnings ratio doesn't work well with stocks with negative earnings. Similary, stocks that buyback their own shares are dificult to value using the price-to-book ratio.

Investors typically use a composite basket of valuation metrics to build robust quantitative value strategies.

In this section, we will filter for stocks with the lowest percentiles on the following metrics:

    1. Price-to-earnings ratio (Equivalent in portuguese: P/L - Preço sobre lucro)
    2. Price-to-book ratio (Equivalent in portuguese: P/VP - Preço sobre Valor Patrimonial)
    3. Price-to-sales ratio (Equivalent in portuguese: P/S - Preço sobre vendas
    4. Enterprise Value divided by earnings before interest, taxes, depreciation, and amortization (EV/EBITDA)
    5. Enterprise Value divided by gross profit (EV/GP)

Some of these metrics aren't provided directly by the IEX Cloud API, and must be computed after pulling raw data.

In [10]:
symbol = 'AAPL'
batch_api_call_url = f'https://sandbox.iexapis.com/stable/stock/market/batch?symbols={symbol} &types=quote,advanced-stats&token={IEX_CLOUD_API_TOKEN}'
data = requests.get(batch_api_call_url).json()

print(data['AAPL']['advanced-stats']['priceToBook'])


# Price-to-earnings ratio
pe_ratio = data[symbol]['quote']['peRatio']

# Price-to-book ratio 
pb_ratio = data['AAPL']['advanced-stats']['priceToBook']

# Price-to-sales ratio 
ps_ratio = data['AAPL']['advanced-stats']['priceToSales']

# Enterprise value divided by earnings before interest, taxes, depreciation, and amortization (EV/EBITDA)
enterprise_value = data['AAPL']['advanced-stats']['enterpriseValue']
ebitda = data['AAPL']['advanced-stats']['EBITDA']
ev_to_ebitda = enterprise_value/ebitda

# Enterprise value divided by Gross Profit (EV/GP)
gross_profit = data['AAPL']['advanced-stats']['grossProfit']
ev_to_gross_profit = enterprise_value/gross_profit

32.42

In [11]:
rv_columns = [
    'Ticker',
    'Price',
    'Number of Shares to Buy',
    'Price-to-Earnings Ratio',
    'PE Percentile',
    'Price-to-Book Ratio',
    'PB Percentile',
    'Price-to-Sales Ratio',
    'PS Percentile',
    'EV/EBITDA',
    'EV/EBITDA Percentile',
    'EV/GP',
    'EV/GP Percentile',
    'RV Score'
]

rv_dataframe = pd.DataFrame(columns = rv_columns)
rv_dataframe

Empty DataFrame
Columns: [Ticker, Price, Number of Shares to Buy, Price-to-Earnings Ratio, PE Percentile, Price-to-Book Ratio, PB Percentile, Price-to-Sales Ratio, PS Percentile, EV/EBITDA, EV/EBITDA Percentile, EV/GP, EV/GP Percentile, RV Score]
Index: []

In [15]:
for symbol_string in symbol_strings[:2]:      
    #batch_api_call_url = f'https://sandbox.iexapis.com/stable/stock/market/batch?symbols={symbol_string} &types=quote,advanced-stats&token={IEX_CLOUD_API_TOKEN}'
    #data = requests.get(batch_api_call_url).json()
    
    for symbol in symbol_string.split(','):
        print(symbol)

AAP
AAPL
ABBV
ABC
ABMD
ABT
ACN
ADBE
ADI
ADM
ADP
ADSK
AEE
AEP
AES
AFL
AIG
AIV
AIZ
AJG
AKAM
ALB
ALGN
ALK
ALL
ALLE
ALXN
AMAT
AMCR
AMD
AME
AMGN
AMP
AMT
AMZN
ANET
ANSS
ANTM
AON
AOS
APA
APD
APH
APTV
ARE
ATO
ATVI
AVB
AVGO
AVY
AWK
AXP
AZO
BA
BAC
BAX
BBY
BDX
BEN
BF.B
BIIB
BIO
BK
BKNG
BKR
BLK
BLL
BMY
BR
BRK.B
BSX
BWA
BXP
C
CAG
CAH
CARR
CAT
CB
CBOE
CBRE
CCI
CCL
CDNS
CDW
CE
CF
CFG
CHD
CHRW
CHTR
CI
CINF
CL
CLX
CMA
CMCSA
CME
CMG
CMI
CMS
CNC
CNP
COF
COG
COO
COP
COST
COTY
CPB
CPRT
CRM
CSCO
CSX
CTAS
CTL
CTSH
CTVA
CTXS
CVS
CVX
CXO
D
DAL
DD
DE
DFS
DG
DGX
DHI
DHR
DIS
DISCA
DISCK
DISH
DLR
DLTR
DOV
DOW
DPZ
DRE
DRI
DTE
DUK
DVA
DVN
DXC
DXCM
EA
EBAY
ECL
ED
EFX
EIX
EL
EMN
EMR
EOG
EQIX
EQR
ES
ESS
ETFC
ETN
ETR
EVRG
EW
EXC
EXPD
EXPE
EXR
F
FANG
FAST
FB
FBHS
FCX
FDX
FE
FFIV
FIS
FISV
FITB
FLIR
FLS
FLT
FMC
FOX
FOXA
FRC
FRT
FTI
FTNT
FTV
GD
GE
GILD
GIS
GL
GLW